site_name: Matchbox
theme:
  name: material
  logo: assets/matchbox_logo_color.png
  favicon: assets/favicon-96x96.png
  palette:
    scheme: matchbox
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - features.md
  - changelog.md
  - matchbox-engine.md
  - matchbox-server.md
  - api.md
  - validation.md
  - docker.md
  - cda.md
  - 'Tutorial: validation': validation-tutorial.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
