server:
  servlet:
    context-path: /matchboxv3
hapi:
  fhir:
    server_address: http://localhost:8080/matchboxv3/fhir
    implementationguides:
      fhir_r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        url: classpath:/hl7.fhir.r4.core.tgz
      fhir_terminology:
        name: hl7.terminology
        version: 5.4.0
        url: classpath:/hl7.terminology#5.4.0.tgz
      fhir_extensions:
        name: hl7.fhir.uv.extensions.r4
        version: 1.0.0
        url: classpath:/hl7.fhir.uv.extensions.r4#1.0.0.tgz
      hl7_fhir_uv_ips:
        name: hl7.fhir.uv.ips
        version: current
        url: file:/Users/oegger/Documents/github/matchbox-ch-elm/src/hl7.fhir.uv.ips-current.tgz
      fhir_eu_lab:
        name: hl7.fhir.eu.laboratory
        version: current
        url: file:/Users/oegger/Documents/github/matchbox-ch-elm/src/hl7.fhir.eu.laboratory-current.tgz
      ch_core:
        name: ch.fhir.ig.ch-core
        version: current
        url: file:/Users/oegger/Documents/github/matchbox-ch-elm/src/ch.fhir.ig.ch-core-current.tgz
      fhir_ch_lab:
        name: ch.fhir.ig.ch-lab-report
        version: current
        url: file:/Users/oegger/Documents/github/matchbox-ch-elm/src/ch.fhir.ig.ch-lab-report-current.tgz
      ch_elm:
        name: ch.fhir.ig.ch-elm
        version: 1.0.0
        url: file:/Users/oegger/Documents/github/matchbox-ch-elm/src/ch.fhir.ig.ch-elm-1.0.0.tgz
    staticLocation: file:/apps/
matchbox:
  fhir:
    context:
      fhirVersion: 4.0.1
      txServer: http://tx.fhir.org
