package ca.uhn.fhir.rest.server;

import ca.uhn.fhir.context.FhirContext;
import ch.ahdis.matchbox.config.property.MatchboxFhirMcpProperties;
import ch.ahdis.matchbox.mcp.ToolFactory;
import ch.ahdis.matchbox.util.CrossVersionResourceUtils;
import ch.ahdis.matchbox.util.http.MatchboxFhirFormat;
import ca.uhn.fhir.jpa.starter.mcp.CallToolResultFactory;
import ca.uhn.fhir.jpa.starter.mcp.Interaction;
import ca.uhn.fhir.jpa.starter.mcp.RequestBuilder;

import ch.ahdis.matchbox.validation.ValidationProvider;
import io.modelcontextprotocol.server.McpServerFeatures;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.spec.McpSchema;

import org.hl7.fhir.r5.model.OperationDefinition.OperationDefinitionParameterComponent;
import org.hl7.fhir.r5.model.Enumerations.OperationParameterUse;
import org.hl7.fhir.r5.model.OperationDefinition;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.stereotype.Component;

import java.io.StringWriter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Component
public class McpMatchboxBridge implements McpBridge {
	private static final Logger logger = LoggerFactory.getLogger(McpMatchboxBridge.class);
  
  public static final String PARAM_REQUEST_ANALYSIS_FROM_CLIENT = "requestAnalysisFromClient";
  public static final String PARAM_VALIDATION_PARAMETERS = "validationparams";

	private final RestfulServer restfulServer;

  private final boolean globalRequestAnalysisFromClient;

	public static final String PROMPT = "You are an AI that helps analyze and interpret FHIR resources and their validation results. " +
            "Focus on the issues with severity labeled 'fatal' or 'error' or 'warning' and provide guidance for the underlying issues and examples of what needs to be fixed. If there are several errors generated by the same source, summarize them." +
            "If you can not help with an issue, tell me." +
            "If there are no issues labeled 'fatal' or 'error' or 'warning', simply reply with: 'The resource is valid'. Nothing more. Else: keep your answer as short as possible. Return your full answer in markdown format.";

	public McpMatchboxBridge(final RestfulServer restfulServer,
                           final MatchboxFhirMcpProperties matchboxFhirMcpProperties) {
		this.restfulServer = restfulServer;
    this.globalRequestAnalysisFromClient = matchboxFhirMcpProperties.isRequestAnalysisFromClient();
	}

	public List<McpServerFeatures.SyncToolSpecification> generateTools() {
    return List.of(
      new McpServerFeatures.SyncToolSpecification(
        ToolFactory.validateFhirResource(),
        (exchange, request) -> getValidationResult(exchange, request, Interaction.VALIDATE)
      ),
      new McpServerFeatures.SyncToolSpecification(
        ToolFactory.listFhirImplementationGuides(),
        (exchange, request) -> getFhirImplementationGuides(request, Interaction.SEARCH)
      ),
      new McpServerFeatures.SyncToolSpecification(
        ToolFactory.listFhirProfilesToValidateFor(),
        (exchange, request) -> getFhirProfilesToValidateFor(request, Interaction.READ)
      ),
      new McpServerFeatures.SyncToolSpecification(
        ToolFactory.listValidationParameters(),
        (exchange, request) -> getExtraValidationParameters(request, Interaction.READ)
      )
    );
	}

	private McpSchema.CallToolResult getFhirProfilesToValidateFor(final McpSchema.CallToolRequest toolRequest,
                                                                final Interaction interaction) {
    final var arguments = toolRequest.arguments();
		var response = new MockHttpServletResponse();
		final String resourceType = (String) arguments.get("resourceType");
		// we need to overwrite it for calling the read interaction
		arguments.put("resourceType", "OperationDefinition");
		arguments.put("id", "-s-validate");
		final String ig = (String) arguments.get("ig");
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				FhirContext fhirR5Context = FhirContext.forR5Cached();
				OperationDefinition operationDefinition = fhirR5Context.newJsonParser().parseResource(OperationDefinition.class, body);
				Object[] profiles = operationDefinition.getParameter().stream()
					.filter(p -> p.getName().equals("profile"))
					.map(OperationDefinitionParameterComponent::getTargetProfile)
					.flatMap(List::stream)
					.filter(targetProfile -> targetProfile.hasExtension("ig-current") && targetProfile.getExtensionByUrl("ig-current").getValueBooleanType().booleanValue())
					.filter(targetProfile -> ig==null || ig.isEmpty() || (targetProfile.hasExtension("ig-id") && targetProfile.getExtensionByUrl("ig-id").getValueStringType().asStringValue().equals(ig)))
					.filter(targetProfile -> resourceType==null || resourceType.isEmpty() || (targetProfile.hasExtension("sd-title") && targetProfile.getExtensionByUrl("sd-title").getValueStringType().asStringValue().startsWith(resourceType)))
					.map( targetProfile -> {
						var map = new HashMap<String, String>();
						map.put("title", targetProfile.getExtensionByUrl("sd-title").getValueStringType().asStringValue());
						map.put("profile", targetProfile.getValue());
						map.put("ig",  targetProfile.getExtensionByUrl("ig-id").getValueStringType().asStringValue());
						return map;
						} ).toArray();
		        return CallToolResultFactory.successPayload(profiles);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

	private McpSchema.CallToolResult getExtraValidationParameters(final McpSchema.CallToolRequest toolRequest,
                                                                final Interaction interaction) {
    final var arguments = toolRequest.arguments();
		var response = new MockHttpServletResponse();
		arguments.put("resourceType", "OperationDefinition");
		arguments.put("id", "-s-validate");
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				FhirContext fhirR5Context = FhirContext.forR5Cached();
				OperationDefinition operationDefinition = fhirR5Context.newJsonParser().parseResource(OperationDefinition.class, body);
				List<OperationDefinitionParameterComponent> parameters = operationDefinition.getParameter().stream()
					.filter(p -> OperationParameterUse.IN.equals(p.getUse()))
					.filter(p -> !"resource".equals(p.getName()))
					.filter(p -> !"profile".equals(p.getName()))
					.peek(p -> p.setUse(null))
          .toList();
				
				
				StringWriter result = new StringWriter();
				result.append("[ ");
        for (final OperationDefinitionParameterComponent parameter : parameters) {
          CrossVersionResourceUtils.serializeR5(parameter, MatchboxFhirFormat.JSON, result);
          result.append(",");
        }
				result.append("]");

				String json = result.toString();
        return CallToolResultFactory.successFhirBody(json);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

	private McpSchema.CallToolResult getFhirImplementationGuides(final McpSchema.CallToolRequest toolRequest,
                                                               final Interaction interaction) {
    final var arguments = toolRequest.arguments();
		var response = new MockHttpServletResponse();
		arguments.put("resourceType", "ImplementationGuide");
		if (arguments.containsKey("includeVersions")) {
			if (arguments.get("includeVersions").equals("false")) {
				Map<String, Object> map = new java.util.HashMap<>();
				map.put("_tag", "http://matchbox.health/fhir/CodeSystem/tag|current");
				arguments.put("query", map);
			}
			arguments.remove("includeVersions");
		} else {
				Map<String, Object> map = new java.util.HashMap<>();
				map.put("_tag", "http://matchbox.health/fhir/CodeSystem/tag|current");
				arguments.put("query", map);
		}
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}
				return CallToolResultFactory.successFhirBody(body);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}	

	private McpSchema.CallToolResult getValidationResult(final McpSyncServerExchange exchange,
                                                       final McpSchema.CallToolRequest toolRequest,
                                                       final Interaction interaction) {
    final var arguments = toolRequest.arguments();
    boolean requestAnalysisFromClient = this.globalRequestAnalysisFromClient;

		final var response = new MockHttpServletResponse();
    final Map<String, String> requestQueryArguments;
		if (arguments.containsKey(PARAM_VALIDATION_PARAMETERS)) {
      requestQueryArguments = HashMap.newHashMap(8);
			String validationParams = (String) arguments.get(PARAM_VALIDATION_PARAMETERS);
			// Parse the validationParams string into a Map
			String[] params = validationParams.split(",");

			for (String param : params) {
				String[] keyValue = param.split("=");
				if (keyValue.length == 2) {
          requestQueryArguments.put(keyValue[0].trim(), keyValue[1].trim());
				}
			}

      if (requestQueryArguments.containsKey(PARAM_REQUEST_ANALYSIS_FROM_CLIENT)) {
        // Override the global configuration if the parameter is present in the request
        requestAnalysisFromClient = Boolean.parseBoolean(String.valueOf(requestQueryArguments.get(PARAM_REQUEST_ANALYSIS_FROM_CLIENT)));
      }
		} else {
      requestQueryArguments = HashMap.newHashMap(1);
		}
    // Disable LLM analysis by Matchbox' LLM, we'll ask the client to do it if necessary
    requestQueryArguments.put(ValidationProvider.PARAM_ANALYZE_ERRORS_WITH_LLM, "false");
    arguments.put("query", requestQueryArguments);

		final var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();

		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				if (requestAnalysisFromClient) {
					body = addAiAnalysis(exchange, body);
				}

				return CallToolResultFactory.successFhirBody(body);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

	public String addAiAnalysis(McpSyncServerExchange exchange, String fhirOperationOutcome) {
		// check if MCP Client supports Sampling
		if (exchange.getClientCapabilities() != null && exchange.getClientCapabilities().sampling() != null) {
				try {
					// create a new Prompt for Sampling
					final McpSchema.TextContent promptContent =
            McpSchema.TextContent.builder(PROMPT + "Here is the validation result: " + fhirOperationOutcome).build();

					// create a new Sampling Message with the USER Role
          final McpSchema.SamplingMessage samplingMessage =
            new McpSchema.SamplingMessage(McpSchema.Role.USER, promptContent);

					// create the sampling request
					final McpSchema.CreateMessageRequest samplingRequest =
            McpSchema.CreateMessageRequest.builder(List.of(samplingMessage), 10_000).build();

					// get the response back from the LLM
					final McpSchema.CreateMessageResult samplingResult = exchange.createMessage(samplingRequest);

					// check if sampling result is valid
					if (samplingResult != null && samplingResult.content() instanceof McpSchema.TextContent textResponse) {
						return textResponse.text();
					} else {
						return fhirOperationOutcome;
					}
				} catch (final Exception e) {
					logger.error(e.getMessage(), e);
					return fhirOperationOutcome;
				} 
		// If the client does NOT support sampling
		} else {
				// add a prompt before the operation outcome 
				final var contentHeader = "Here is the validation result: ";
				return PROMPT + "\n" + contentHeader + fhirOperationOutcome;
		}
	}
}
