package ca.uhn.fhir.rest.server;

import ca.uhn.fhir.context.FhirContext;
import ch.ahdis.matchbox.config.property.MatchboxFhirMcpProperties;
import ch.ahdis.matchbox.engine.exception.MatchboxUnsupportedFhirVersionException;
import ch.ahdis.matchbox.providers.BundleResourceProvider;
import ch.ahdis.matchbox.util.CrossVersionResourceUtils;
import ch.ahdis.matchbox.util.http.MatchboxFhirFormat;
import ca.uhn.fhir.jpa.starter.mcp.CallToolResultFactory;
import ca.uhn.fhir.jpa.starter.mcp.Interaction;
import ca.uhn.fhir.jpa.starter.mcp.RequestBuilder;

import ch.ahdis.matchbox.validation.ValidationProvider;
import io.modelcontextprotocol.server.McpSyncServerExchange;
import io.modelcontextprotocol.spec.McpSchema;

import jakarta.annotation.Nullable;
import org.hl7.fhir.r5.model.Bundle;
import org.hl7.fhir.r5.model.OperationDefinition.OperationDefinitionParameterComponent;
import org.hl7.fhir.r5.model.Enumerations.OperationParameterUse;
import org.hl7.fhir.r5.model.OperationDefinition;
import org.hl7.fhir.r5.model.Resource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.mcp.annotation.McpTool;
import org.springframework.ai.mcp.annotation.McpToolParam;
import org.springframework.mock.web.MockHttpServletResponse;
import org.springframework.stereotype.Component;

import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static java.util.HashMap.newHashMap;

@Component
public class McpMatchboxBridge {
	private static final Logger logger = LoggerFactory.getLogger(McpMatchboxBridge.class);
  
  public static final String PARAM_REQUEST_ANALYSIS_FROM_CLIENT = "requestAnalysisFromClient";
  public static final String PARAM_VALIDATION_PARAMETERS = "validationparams";

	private final RestfulServer restfulServer;
  private final BundleResourceProvider bundleResourceProvider;

  private final boolean globalRequestAnalysisFromClient;

	public static final String PROMPT = "You are an AI that helps analyze and interpret FHIR resources and their validation results. " +
            "Focus on the issues with severity labeled 'fatal' or 'error' or 'warning' and provide guidance for the underlying issues and examples of what needs to be fixed. If there are several errors generated by the same source, summarize them." +
            "If you can not help with an issue, tell me." +
            "If there are no issues labeled 'fatal' or 'error' or 'warning', simply reply with: 'The resource is valid'. Nothing more. Else: keep your answer as short as possible. Return your full answer in markdown format.";

	public McpMatchboxBridge(final RestfulServer restfulServer,
                           final MatchboxFhirMcpProperties matchboxFhirMcpProperties,
                           final BundleResourceProvider bundleResourceProvider) {
		this.restfulServer = restfulServer;
    this.globalRequestAnalysisFromClient = matchboxFhirMcpProperties.isRequestAnalysisFromClient();
    this.bundleResourceProvider = bundleResourceProvider;
	}

  @McpTool(name = "list-fhir-profiles-to-validate-for",
    description = "List FHIR Profiles available for validation.",
    annotations = @McpTool.McpAnnotations(readOnlyHint = true, destructiveHint = false, idempotentHint = true, openWorldHint = false))
	private McpSchema.CallToolResult getFhirProfilesToValidateFor(
    @McpToolParam(description = "FHIR resource type list profiles for, if not provided all profiles for all resources and logical models are listed", required = false)
    final @Nullable String resourceType,
    @McpToolParam(description = "package id to list profiles for, if not provided all profiles for the latest ig versions are listed", required = false)
    final @Nullable String ig
  ) {
    final HashMap<String, Object> arguments = HashMap.newHashMap(2);
		var response = new MockHttpServletResponse();
		arguments.put("resourceType", "OperationDefinition");
		arguments.put("id", "-s-validate");
    final var interaction = Interaction.SEARCH;
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				FhirContext fhirR5Context = FhirContext.forR5Cached();
				OperationDefinition operationDefinition = fhirR5Context.newJsonParser().parseResource(OperationDefinition.class, body);
				Object[] profiles = operationDefinition.getParameter().stream()
					.filter(p -> p.getName().equals("profile"))
					.map(OperationDefinitionParameterComponent::getTargetProfile)
					.flatMap(List::stream)
					.filter(targetProfile -> targetProfile.hasExtension("ig-current") && targetProfile.getExtensionByUrl("ig-current").getValueBooleanType().booleanValue())
					.filter(targetProfile -> ig==null || ig.isEmpty() || (targetProfile.hasExtension("ig-id") && targetProfile.getExtensionByUrl("ig-id").getValueStringType().asStringValue().equals(ig)))
					.filter(targetProfile -> resourceType==null || resourceType.isEmpty() || (targetProfile.hasExtension("sd-title") && targetProfile.getExtensionByUrl("sd-title").getValueStringType().asStringValue().startsWith(resourceType)))
					.map( targetProfile -> {
						var map = new HashMap<String, String>();
						map.put("title", targetProfile.getExtensionByUrl("sd-title").getValueStringType().asStringValue());
						map.put("profile", targetProfile.getValue());
						map.put("ig",  targetProfile.getExtensionByUrl("ig-id").getValueStringType().asStringValue());
						return map;
						} ).toArray();
		        return CallToolResultFactory.successPayload(profiles);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

  @McpTool(name = "list-validation-parameters",
    description = "List additional available parameters for validation",
    annotations = @McpTool.McpAnnotations(readOnlyHint = true, destructiveHint = false, idempotentHint = true, openWorldHint = false))
	private McpSchema.CallToolResult getExtraValidationParameters() {
    final HashMap<String, Object> arguments = HashMap.newHashMap(2);
		var response = new MockHttpServletResponse();
		arguments.put("resourceType", "OperationDefinition");
		arguments.put("id", "-s-validate");
    final var interaction = Interaction.READ;
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				FhirContext fhirR5Context = FhirContext.forR5Cached();
				OperationDefinition operationDefinition = fhirR5Context.newJsonParser().parseResource(OperationDefinition.class, body);
				List<OperationDefinitionParameterComponent> parameters = operationDefinition.getParameter().stream()
					.filter(p -> OperationParameterUse.IN.equals(p.getUse()))
					.filter(p -> !"resource".equals(p.getName()))
					.filter(p -> !"profile".equals(p.getName()))
					.peek(p -> p.setUse(null))
          .toList();
				
				
				StringWriter result = new StringWriter();
				result.append("[ ");
        for (final OperationDefinitionParameterComponent parameter : parameters) {
          CrossVersionResourceUtils.serializeR5(parameter, MatchboxFhirFormat.JSON, result);
          result.append(",");
        }
				result.append("]");

				String json = result.toString();
        return CallToolResultFactory.successFhirBody(json);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

  @McpTool(name = "list-fhir-igs",
    description = "List FHIR Implementation Guides available for validation",
    annotations = @McpTool.McpAnnotations(readOnlyHint = true, destructiveHint = false, idempotentHint = true, openWorldHint = false))
	private McpSchema.CallToolResult getFhirImplementationGuides(
    @McpToolParam(description = "include older versions of the installed FHIR Implementation Guides, defaults to false", required = false)
    final @Nullable Boolean includeVersions
  ) {
    final HashMap<String, Object> arguments = HashMap.newHashMap(2);
		var response = new MockHttpServletResponse();
		arguments.put("resourceType", "ImplementationGuide");
		if (includeVersions == null || includeVersions) {
				arguments.put("query", Map.of("_tag", "http://matchbox.health/fhir/CodeSystem/tag|current"));
		}
    final var interaction = Interaction.SEARCH;
		var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}
				return CallToolResultFactory.successFhirBody(body);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}	

  @McpTool(name = "validate-fhir-resource",
    description = "Validate a FHIR resource or logical model against a profile and return a FHIR OperationOutcome indicating the result of the validation",
    annotations = @McpTool.McpAnnotations(readOnlyHint = true, destructiveHint = false, idempotentHint = true, openWorldHint = false))
	private McpSchema.CallToolResult getValidationResult(
    final McpSyncServerExchange exchange,
    @McpToolParam(description = "The FHIR resource or logical model to validate in XML or JSON format")
    final String resource,
    @McpToolParam(description = "The FHIR profile to validate against")
    final String profile,
    @McpToolParam(description = "Additional validation parameters separated by ',' (comma). For example: 'txServer=http://tx.fhir.org,txUseEcosystem=false'.", required = false)
    final @Nullable String validationparams
  ) {
    final var interaction = Interaction.VALIDATE;
    boolean requestAnalysisFromClient = this.globalRequestAnalysisFromClient;

		final var response = new MockHttpServletResponse();
    final Map<String, String> requestQueryArguments;
		if (validationparams != null) {
      requestQueryArguments = newHashMap(8);
			// Parse the validationParams string into a Map
			String[] params = validationparams.split(",");

			for (String param : params) {
				String[] keyValue = param.split("=");
				if (keyValue.length == 2) {
          requestQueryArguments.put(keyValue[0].trim(), keyValue[1].trim());
				}
			}

      if (requestQueryArguments.containsKey(PARAM_REQUEST_ANALYSIS_FROM_CLIENT)) {
        // Override the global configuration if the parameter is present in the request
        requestAnalysisFromClient = Boolean.parseBoolean(String.valueOf(requestQueryArguments.get(PARAM_REQUEST_ANALYSIS_FROM_CLIENT)));
      }
		} else {
      requestQueryArguments = newHashMap(1);
		}
    // Disable LLM analysis by Matchbox' LLM, we'll ask the client to do it if necessary
    requestQueryArguments.put(ValidationProvider.PARAM_ANALYZE_ERRORS_WITH_LLM, "false");
    final Map<String, Object> arguments = HashMap.newHashMap(3);
    arguments.put("query", requestQueryArguments);
    arguments.put("resource", resource);
    if (profile != null && !profile.isBlank()) {
      arguments.put("profile", profile);
    }

		final var request = new RequestBuilder(restfulServer, arguments, interaction).buildRequest();
    request.setContent(resource.getBytes(StandardCharsets.UTF_8));

		try {
			restfulServer.handleRequest(interaction.asRequestType(), request, response);
			var status = response.getStatus();
			var body = response.getContentAsString();

			if (status >= 200 && status < 300) {
				if (body.isBlank()) {
					return CallToolResultFactory.failure("Empty successful response for " + interaction);
				}

				if (requestAnalysisFromClient) {
					body = addAiAnalysis(exchange, body);
				}

				return CallToolResultFactory.successFhirBody(body);
			} else {
				return CallToolResultFactory.failure(String.format("FHIR server error %d: %s", status, body));
			}
		} catch (Exception e) {
			logger.error(e.getMessage(), e);
			return CallToolResultFactory.failure("Unexpected error: " + e.getMessage());
		}
	}

  @McpTool(name = "get-profiles-for-document-bundle",
    description = "Get the list of FHIR StructureDefinition profiles that match a FHIR document Bundle resource",
    annotations = @McpTool.McpAnnotations(readOnlyHint = true, destructiveHint = false, idempotentHint = true, openWorldHint = false))
  private McpSchema.CallToolResult getProfilesForDocumentBundle(
    @McpToolParam(description = "The FHIR Bundle resource of type document to get the profiles for, in XML or JSON format")
    final String bundleSerialized
  ) {
    final var bundleBytes = bundleSerialized.trim().getBytes(StandardCharsets.UTF_8);
    final var requestVersion = this.restfulServer.getFhirContext().getVersion().getVersion();
    final var requestFormat = bundleBytes[0] == '{' ? MatchboxFhirFormat.JSON : MatchboxFhirFormat.XML;
    final Resource resource;
    try {
      resource = switch (requestVersion) {
        case R4 -> CrossVersionResourceUtils.parseR4AsR5(bundleBytes, requestFormat);
        case R4B -> CrossVersionResourceUtils.parseR4bAsR5(bundleBytes, requestFormat);
        case R5 -> CrossVersionResourceUtils.parseR5(bundleBytes, requestFormat);
        default -> throw new MatchboxUnsupportedFhirVersionException("McpMatchboxBridge.getProfilesForDocumentBundle",
                                                                     requestVersion);
      };
    } catch (final Exception e) {
      return CallToolResultFactory.failure("Failed to parse the provided Bundle: " + e.getMessage());
    }
    if (!(resource instanceof final Bundle bundle)) {
      return CallToolResultFactory.failure("The provided resource is not a Bundle");
    }
    final var analysis = this.bundleResourceProvider.getProfilesForBundle(bundle);
    if (analysis == null) {
      return CallToolResultFactory.failure("The Bundle could not be analyzed as a document");
    }
    return CallToolResultFactory.successPayload(analysis.profiles().toArray(new BundleResourceProvider.ValidationProfile[0]));
  }

	private String addAiAnalysis(McpSyncServerExchange exchange, String fhirOperationOutcome) {
		// check if MCP Client supports Sampling
		if (exchange.getClientCapabilities() != null && exchange.getClientCapabilities().sampling() != null) {
				try {
					// create a new Prompt for Sampling
					final McpSchema.TextContent promptContent =
            McpSchema.TextContent.builder(PROMPT + "Here is the validation result: " + fhirOperationOutcome).build();

					// create a new Sampling Message with the USER Role
          final McpSchema.SamplingMessage samplingMessage =
            new McpSchema.SamplingMessage(McpSchema.Role.USER, promptContent);

					// create the sampling request
					final McpSchema.CreateMessageRequest samplingRequest =
            McpSchema.CreateMessageRequest.builder(List.of(samplingMessage), 10_000).build();

					// get the response back from the LLM
					final McpSchema.CreateMessageResult samplingResult = exchange.createMessage(samplingRequest);

					// check if sampling result is valid
					if (samplingResult != null && samplingResult.content() instanceof McpSchema.TextContent textResponse) {
						return textResponse.text();
					} else {
						return fhirOperationOutcome;
					}
				} catch (final Exception e) {
					logger.error(e.getMessage(), e);
					return fhirOperationOutcome;
				} 
		// If the client does NOT support sampling
		} else {
				// add a prompt before the operation outcome 
				final var contentHeader = "Here is the validation result: ";
				return PROMPT + "\n" + contentHeader + fhirOperationOutcome;
		}
	}
}
