# This workflow will test the Javadoc of a Java project with Maven
name: Javadoc test

on:
  workflow_dispatch:
  push:
    branches: [main, matchbox_v5]
  pull_request:
    branches: [main, matchbox_v5]

jobs:
  test-javadoc:
    runs-on: ubuntu-latest
    env:
      # Read the HAPI FHIR build from GitHub Packages, see the 'github' repository in pom.xml
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAVEN_ARGS: --global-settings ${{ github.workspace }}/.github/maven-settings.xml
    steps:
      - name: Checkout the project
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Test the Javadoc
        run: mvn --batch-mode --no-transfer-progress javadoc:aggregate -f pom.xml
