# This workflow will build and test a Java project with Maven
name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 21
          distribution: adopt
          cache: maven

      - name: Install maven (ubuntu-slim)
        if: matrix.os == 'ubuntu-slim'
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run the engine tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-engine test

      - name: Run the GazelleApiR4Test tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dtest=GazelleApiR4Test test


      - name: Run the TransformTest tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dtest=TransformTest test


      - name: Run the MatchboxApiR4Test tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dscheduling_disabled=true -Dtest=MatchboxApiR4Test test


      - name: Run the MatchboxApiR4BTest tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dtest=MatchboxApiR4BTest test


      - name: Run the MatchboxApiR5Test tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dtest=MatchboxApiR5Test test


      - name: Run the MatchboxApiR5onR4Test tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-server -Dtest=MatchboxApiR5onR4Test test
