# This workflow will build and test a Java project with Maven
name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        # https://github.com/actions/setup-java#usage
        with:
          java-version: 25
          distribution: adopt
          cache: maven

      - name: Run the engine tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -pl matchbox-engine test

      - name: Run the core tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -Dgroups='core' test

      - name: Run the validation tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -Dgroups='validation' test

      - name: Run the Gazelle API tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -Dgroups='gazelle' test

      - name: Run the mapping tests in Maven
        timeout-minutes: 15
        run: mvn --batch-mode --no-transfer-progress --update-snapshots -Dgroups='mapping' test
